### ISSUE TITLE
Dependency on `nix-prefetch-git` not included in PATH

### ISSUE THREAD

**Issue by TylerRichie** [tenx-tech/cargo2nix#60]
Git dependencies depend on the `nix-prefetch-git` binary (available in nixpkgs) being included on the system path. `cargo2nix` relies on the end-user to do this themselves, otherwise it fails on projects with git dependencies.

This could be fixed with a `makeWrapper` derivation that includes `nix-prefetch-git` in the `PATH` when invoking `cargo2nix`.

**Comment by ebkalderon** [comment]
@TylerRichie Thanks for reporting this bug! It should be fixed in the latest `master` by #62. Please try it out and let us know if you experience any issues. We can always re-open if similar problems resurface.
