### ISSUE TITLE
Add some sample projects

### ISSUE THREAD

**Issue by ebkalderon** [tenx-tech/cargo2nix#69]
I believe we could improve the user experience a bit by providing a few sample Cargo crates and crate workspaces converted to use `cargo2nix`. This would provide useful examples for potential users looking to convert their projects, but might not know exactly how to get started with the instructions given in the README.

Example scenarios:

1. Single crate (`lib` and/or `bin`, combination doesn't exactly matter to `cargo2nix`)
2. Multi-crate workspace
3. Crate with one or more feature flags
4. Crate with extra directories to be included (e.g. a `proto` directory for Protobuf projects)
5. Crate with test runner and some `nativeBuildDependencies`
6. Crate with a custom crate override on a sub-dependency

**Comment by kolloch** [comment]
It would be so cool if we somehow shared a test repository with `crate2nix` and we got an overview of general feature support and crate compatibility.

**Comment by ebkalderon** [comment]
@kolloch Agreed! That sounds quite useful, actually.

**Comment by ebkalderon** [comment]
Where would you like to have this repository reside and what should it be called, by the way? I presume it would be under the `nix-community` organization?
