### ISSUE TITLE
Use a templating engine for code generation

### ISSUE THREAD

**Issue by trha** [tenx-tech/cargo2nix#71]

**Comment by ebkalderon** [comment]
Some candidates solutions to look into:

* [`handlebars`](https://github.com/sunng87/handlebars-rust) (Handlebars compatible)
* [`liquid`](https://github.com/cobalt-org/liquid-rust) (Shopify/Liquid compatible)
* [`tera`](https://github.com/Keats/tera) (Jinja2/Django-like)
