### ISSUE TITLE
Improve error message when Cargo.lock needs updating

### ISSUE THREAD

**Issue by ebkalderon** [tenx-tech/cargo2nix#75]
When `cargo2nix -f` is run, it executes Cargo's dependency resolution algorithm in `--locked` mode, meaning that the `Cargo.lock` is treated as immutable. Normally, if the `Cargo.lock` is out of sync with the contents of the `Cargo.toml` (e.g. a crate version was bumped or a dependency was added or removed), Cargo will silently update the `Cargo.lock` whenever it is next invoked by the user. But when Cargo is run in `locked` mode, the application will exit early and prompt the user to update the lockfile explicitly instead.

Currently, the `cargo2nix` tool exits in this scenario with a crude and ungraceful panic:

```
$ cargo2nix -f
    Updating crates.io index
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "the lock file /home/user/foo/Cargo.lock needs to be updated but --locked was passed to prevent this" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

We should eliminate this `unwrap()` and handle the error properly, ideally printing some additional context describing how to update the `Cargo.lock`. In this case, the user would have to do one of the following:

1. Running `cargo build`, `cargo test`, etc. at least once in the command-line.
2. Running `cargo update -p <crate>...` to update the specific packages affected.

**Comment by ebkalderon** [comment]
For context, we execute the Cargo depedency resolution algorithm in `--locked` mode is to ensure predictable and reproducible behavior. `cargo2nix` is intended to produce a direct translation of the `Cargo.lock` into a `Cargo.nix` without modifying the original. If the lockfile is out of date, we strive to always alert the user to update explicitly instead of applying unexpected silent changes.

**Comment by ebkalderon** [comment]
This issue has technically been solved by #86, since the underlying Cargo error messages now get bubbled up and pretty-printed instead of panicking.

**Comment by alexanderkjeldaas** [comment]
Was hit by this.  I think the fact that this is from some underlying tool is incomprehensible unless the user knows exactly what is happening here.

If the error was wrapped in a message indicating in what context this happened, it would help a lot.

**Comment by psionic-k** [comment]
`ErrorMessage { msg: "the lock file /home/user/foo/Cargo.lock needs to be updated`

#303 #250
