### ISSUE TITLE
Error building OpenSSL

### ISSUE THREAD

**Issue by vbrandl** [tenx-tech/cargo2nix#96]
I have a crate that depends on OpenSSL through `git2` to be able to clone repositories via `https`.

When trying to build OpenSSL, `nix-build` fails with

```
<snip>
*** Installing runtime programs                                                                                                                                           
install apps/openssl -> /nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/bin/openssl                                                                            
install ./tools/c_rehash -> /nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/bin/c_rehash                                                                       
rm: cannot remove '/nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/etc/ssl/misc': No such file or directory                                                    
builder for '/nix/store/ydyxwaq8zkqpq3pn63az1mbqaai45lvi-openssl-1.1.1d.drv' failed with exit code 1                                                                      
building '/nix/store/92l795axyqs3s8vc9828pj653k15zpcf-openssl-sys-0.9.54.tar.gz.drv'...                                                                                   
cannot build derivation '/nix/store/019pl8a07ys1nkkscm7l271743rxfflg-openssl.drv': 1 dependencies couldn't be built                                                       
cannot build derivation '/nix/store/vvin0c5x2yzqi36bmm38pgfl24qjry28-exports.sh.drv': 1 dependencies couldn't be built                                                    
cannot build derivation '/nix/store/361abpqh31fprx0jldn3kqbbgil87px7-openssl-sys-propagate-env.drv': 1 dependencies couldn't be built                                     
cannot build derivation '/nix/store/wmgmrzi2ixz26zmbw7zrvd8yrs5hs2rk-crate-git_test-0.1.0.drv': 1 dependencies couldn't be built                                          
error: build of '/nix/store/wmgmrzi2ixz26zmbw7zrvd8yrs5hs2rk-crate-git_test-0.1.0.drv' failed
```

I created a small testcase to reproduce the issue: https://github.com/vbrandl/cargo2nix-git2-testcase. It uses the current `HEAD` (`e912ed483e980dfb4666ae0ed17845c4220e5e7c`) of the mozilla overlay.

I tried building the same testcase using [crate2nix](https://github.com/kolloch/crate2nix), which build the project but resulted in runtime errors when executing the binary (https://github.com/kolloch/crate2nix/issues/103)

**Comment by ebkalderon** [comment]
Thanks for creating a minimal verifiable example for this, @vbrandl! ❤️

It seems that you have not pinned your Nixpkgs version in your example (it imports `<nixpkgs>`), so I will not be able to precisely replicate your failed `openssl` build on my machine, unfortunately.

But that should be okay. It seems that `openssl-1.1.1d` is the latest version in `nixpkgs-unstable` currently, so I'll just be assuming Nixpkgs commit `eb3e75e78832461c2462b9a5280b8a19cfc5246b` for now as I try to replicate the issue.

**Comment by ebkalderon** [comment]
Hmm, it seems that the failure is occurring on [pkgs/development/libraries/openssl/default.nix#L116](https://github.com/NixOS/nixpkgs/blob/eb3e75e78832461c2462b9a5280b8a19cfc5246b/pkgs/development/libraries/openssl/default.nix#L116) in Nixpkgs when building our patched OpenSSL from source, but it isn't occurring upstream. I'm investigating further.

**Comment by ebkalderon** [comment]
I can replicate the issue with our `patchOpenssl` override in [overlay/overrides.nix](https://github.com/tenx-tech/cargo2nix/blob/master/overlay/overrides.nix#L6-L18) with the following expression:

```nix
let
  nixpkgs = builtins.fetchGit {
    url = https://github.com/NixOS/nixpkgs;
    rev = "eb3e75e78832461c2462b9a5280b8a19cfc5246b";
  };
in
  with import nixpkgs {}; (openssl.override {
    # We only need `perl` at build time. It's also used as the interpreter for one
    # of the produced binaries (`c_rehash`), but they'll be removed later.
    perl = buildPackages.buildPackages.perl;
  }).overrideAttrs (drv: {
    installTargets = "install_sw";
    outputs = [ "dev" "out" "bin" ];
    # Remove binaries, we need only libraries.
    postFixup = ''
      ${drv.postFixup}
      rm -rf $bin/*
    '';
  })
```

This expression produces a very similar error to yours:

```
*** Installing runtime programs
install apps/openssl -> /nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/bin/openssl
install ./tools/c_rehash -> /nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/bin/c_rehash
rm: cannot remove '/nix/store/6dgjjir56h5bjsjcvhbjy0kz4lzjiggn-openssl-1.1.1d/etc/ssl/misc': No such file or directory
builder for '/nix/store/ydyxwaq8zkqpq3pn63az1mbqaai45lvi-openssl-1.1.1d.drv' failed with exit code 1
```

This issue doesn't occur on older versions of Nixpkgs with `openssl-1.0.2s`. For example, after replacing the pinned revision shown above with `47b551c6a854a049045455f8ab1b8750e7b00625` (the revision used by `cargo2nix` to build itself), everything builds fine without errors.

I guess there was a change in how OpenSSL behaves upstream that is causing our override to break. Apparently, `openssl-1.1.1s` already checks for unnecessary dependencies on Perl in the output, making our `patchOpenssl` override unnecessary. Perhaps we could check the OpenSSL version string at evaluation time and disable the override if it's `>=1.1.XY`?

CC @trha

**Comment by ebkalderon** [comment]
It seems that `openssl` in older versions of Nixpkgs defaults to [`openssl_1_0_2`](https://github.com/NixOS/nixpkgs/blob/47b551c6a854a049045455f8ab1b8750e7b00625/pkgs/top-level/all-packages.nix#L12766), but in newer versions it defaults to [`openssl_1_1`](https://github.com/NixOS/nixpkgs/blob/eb3e75e78832461c2462b9a5280b8a19cfc5246b/pkgs/top-level/all-packages.nix#L13736-L13739).

By changing the `patchOpenssl` override in `overlay/overrides.nix` from `pkgs.openssl.override` to `pkgs.openssl_1_0_2.override` and running `NIXPKGS_ALLOW_INSECURE=1 nix-build` in your repository, I'm able to build your test project just fine with the newest Nixpkgs, so I can confirm that something broke in between OpenSSL 1.0 and 1.1 in terms of how the project is built.

I think we should fix the override to behave better with newer versions of OpenSSL, or disable it entirely if applicable.

**Comment by ebkalderon** [comment]
As far as I can tell, cross-compiling OpenSSL 1.1 is still largely broken in current Nixpkgs. Given the following expression:

```nix
{
  system ? builtins.currentSystem,
  crossSystem ? null,
}:
with import <nixpkgs> { inherit system crossSystem; };
openssl
```

And the following build command:

```bash
nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/eb3e75e78832461c2462b9a5280b8a19cfc5246b.tar.gz
```

I can confirm the following results:

`system` | `crossSystem` | Result
----|----|----
`x86_64-linux` | `null` | Works
`x86_64-darwin` | `null` | Works
`x86_64-linux` | `musl64` | Works
`x86_64-darwin` | `musl64` | Fails
`x86_64-linux` | `gnu64` | Fails
`x86_64-darwin` | `gnu64` | Fails

Since `patchOpenssl` was originally added to support cross-compilation and isn't needed for native builds, let's disable it if the host and build platforms match. I can confirm I'm able to build `cargo2nix-git2-testcase` with it! 😁

**Comment by ebkalderon** [comment]
@vbrandl Now that #99 has been merged, you should be able to build `cargo2nix-git2-testcase` after switching `cargo2nix` to `ref = "master"`. Please do let us know if you run into further issues. Thanks for reporting the breakage!

**Comment by vbrandl** [comment]
Thanks for your fast reply.

I'm currently building the current master and will test if everything works.

**Comment by ebkalderon** [comment]
Sounds good! We can re-open the issue if the issue still hasn't been solved.
