### ISSUE TITLE
Cannot write Cargo.nix directly

### ISSUE THREAD

**Issue by vbrandl** [tenx-tech/cargo2nix#97]
I installed the latest version (0.8.2) of `cargo2nix` yesterday using `nix-env -iA package -f https://github.com/tenx-tech/cargo2nix/tarball/master`.

I cannot create `Cargo.nix` directly using `cargo2nix -f`. It panics with `Invalid cross-device link (os error 18)`:

```
$ cargo2nix -f
error: could not write file to Cargo.nix

Caused by:
  failed to persist temporary file: Invalid cross-device link (os error 18)
```

As a workaround, `cargo2nix -s > Cargo.nix` worked for me.

I'm using Linux on a 5.5.9 Kernel using ext4 as filesystem.

**Comment by ebkalderon** [comment]
Thanks for reporting this issue, @vbrandl! Are you running inside a Docker image or have a separate block device for `/tmp`, by any chance? This error seems to be occurring [here](https://github.com/tenx-tech/cargo2nix/blob/master/src/main.rs#L167), which atomically persists the temporary `Cargo.nix` file to its permanent location using the rename call [here](https://github.com/Stebalien/tempfile/blob/master/src/file/imp/unix.rs#L112).

Perhaps we could add an `or_else()` branch which attempts to `std::fs::copy()` the file if `NamedTempFile::persist()` fails?

**Comment by ebkalderon** [comment]
I've created https://github.com/tenx-tech/cargo2nix/pull/98 with an attempted fix. This is a very strange issue, since I haven't been able to replicate it on neither NixOS nor macOS. Would you mind trying out this branch on your machine and see if it fixes the problem?

**Comment by vbrandl** [comment]
No not running inside a container and `/tmp` is just a `tmpfs`.

I'll try the branch from #98 once I've tested #99

**Comment by ebkalderon** [comment]
Hmm, the `tmpfs` might very well be the cause of the issue. I just confirmed that both the NixOS and macOS machines I have at my disposal have a single unified partition for `/` with no special handling for `/tmp`, which is presumably why I never encountered this issue. Hope the change fixes the problem for you!

**Comment by vbrandl** [comment]
#98 solves the issue for me. The error does not occur anymore

**Comment by ebkalderon** [comment]
@vbrandl Awesome! I'm so glad it worked for you. Thanks for reporting this bug, and I hope that this resolves the issue for all systems with `tmpfs` mounts.
